### ISSUE TITLE
Further maintenance of this project

### ISSUE THREAD

**Issue by tuanito** [go-numb/go-ftx#2]
Hi,

I would like to use your project and extend it. Would you prefer that we work in the same project or would you prefer me to fork a new project from yours ? 

Kind regards.

Tuan.

**Comment by go-numb** [comment]
Hi, tuanito.
msg thx.

Package was newly updated.

add to
-websocket for private
-modify / trigger order
-funding
-coins
-custom sort
-test.go

levToken, options will be released after using it in actual operation.


I'm glad, if i can join in development.

**Comment by tuanito** [comment]
Hello,

Sorry for my delay in answering. I would be very glad to contribute and
have locally done some mods on your code to use more FTX API (and got rid
of some bugs) . Could you please add me as a developper ?

My login on github is tuanito. I am not sure how tto apply as a contributor
on github as this is my first time.

Please let me know asap when I am a contributor and can contribute.

I have currently done the following things :
-added Subaccount() method to Client object,
-corrected a compilation bug

Thanks a lot.

Tuan
