### ISSUE TITLE
Example of recovery of the connection

### ISSUE THREAD

**Issue by stephencheng** [go-numb/go-ftx#24]
By any chance that an example of re-connect to the web socket server could be provided?

I am getting below exception very offten due to various of reasons:

```
github.com/go-numb/go-ftx@v0.0.0-20210404151642-7a310724075d/realtime/websocket.go:161: [ERROR]: msg error: read tcp 192.168.1.101:61155->104.18.27.153:443: read: operation timed out
```

Is this recoverable ?  how ?

Thanks

**Comment by SC4RECOIN** [comment]
you could capture `realtime.ERROR` like you would  other responses like `realtime.TRADES` and attempt to reconnect
