### ISSUE TITLE
Invalid authenticator code in requesting Withdraw

### ISSUE THREAD

**Issue by HowJMay** [go-numb/go-ftx#46]
Hi I am using this awesome package for withdrawing money from ftx, but I am always meeting the following error.
`APIError: status=400, message=Invalid authenticator code`

Do you have idea how can I solve this problem. I have provided both password and 2fa code, but it doesn't work at all

**Comment by marvin-hansen** [comment]
Try to withdraw without 2FA.

Please make sure:
* You specific sub-account name when using sub-account
* API Key & secret match 
* Disable 2FA 

I ran a bunch of private requests against a sub-account of mine, and never got any auth error. Also, I reviewed the signature code in auth/auth.go and it fully complies with the FTX specification so the code is correct as far as I can tell. 

Please try to withdraw without 2FA and see if that fixes the problem.

**Comment by HowJMay** [comment]
Thanks for your kind reply. I found I can't use the 2fa code of subaccount. It works fine now!
